# 禁用Jekyll
# 这是一个纯静态站点，不需要Jekyll处理
theme: null
plugins: []

# 排除所有Jekyll相关文件
exclude:
  - .git
  - .github
  - README.md
  - "*.md"
  - Gemfile
  - Gemfile.lock
  - _site
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - vendor

# 确保picgo目录被包含
include:
  - picgo
